# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 19:05
from __future__ import unicode_literals

from django.db import migrations

import csv


def rater_data(apps, schema_editor):
    Rater = apps.get_model("movie_app", "Rater")

    with open("u.user") as outfile:
        rater = csv.DictReader(outfile, fieldnames=["user_id", "age", "gender", "occupation", "zip_code"],
                               delimiter="|")

        for row in rater:
            Rater.objects.create(user_id=int(row['user_id']), age=int(row['age']), gender=row['gender'],
                                 occupation=row['occupation'], zip_code=row['zip_code'])

    # raise Exception('yay')

def movie_data(apps, schema_editor):
    Movie = apps.get_model("movie_app", "Movie")
    with open("u.item", encoding="latin1", delimiter="\t") as outfile:
        movie = outfile.read()

        for row in movie:
            pass


def ratings_data(apps, schema_editor):
    Movie = apps.get_model("movie_app", "Movie")
    Rater = apps.get_model("movie_app", "Rater")
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(rater_data)  # add with commas here

    ]
