# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 19:05
from __future__ import unicode_literals

from django.db import migrations

import csv


def rater_data(apps, schema_editor):
    with open("u.user", encoding="latin1") as outfile:
        rater =read(outfile, fieldnames=["user_id", "age", "gender", "occupation", "zip_code"])

        for row in rater:
            pass


def movie_data(apps, schema_editor):
    pass

def ratings_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
    ]
