# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 02:03
from __future__ import unicode_literals

from django.db import migrations

import csv


def ratings_data(apps, schema_editor):
    Movie = apps.get_model("movie_app", "Movie")
    Rater = apps.get_model("movie_app", "Rater")
    Rating = apps.get_model("movie_app", "Rating")

    with open("u.data") as outfile:
        rating = csv.DictReader(outfile, fieldnames=["user_id", "item_id", "rating", "timestamp"], delimiter="\t")

        for row in rating:
            temp_user_id = Rater.objects.get(user_id=row['user_id'])
            temp_movie_id = Movie.objects.get(movie_id=row['item_id'])
            Rating.objects.create(user_id=temp_user_id, item_id=temp_movie_id,
                                  rating=int(row['rating']), timestamp=int(row['timestamp']))

    # raise Exception('yay3')


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20160608_0200'),
    ]

    operations = [
        migrations.RunPython(ratings_data)

    ]
